/* Automatically generated nanopb field definitions */
/* Generated by custom CMake script from LoRa/docs/telemetry-message.proto */

#include "telemetry/telemetry-message.pb.h"
#include <pb_common.h>

const pb_msgdesc_t TelemetryMessage_msg = {
    .field_count = 4,
    .fields = TelemetryMessage_fields
};

const pb_field_t TelemetryMessage_fields[5] = {
    {1, PB_LTYPE_FIXED32, offsetof(TelemetryMessage, field_1), NULL, NULL, (pb_field_long_t) 0},
    {2, PB_LTYPE_FIXED32, offsetof(TelemetryMessage, field_2), NULL, NULL, (pb_field_long_t) 0},
    {3, PB_LTYPE_FIXED32, offsetof(TelemetryMessage, field_3), NULL, NULL, (pb_field_long_t) 0},
    {4, PB_LTYPE_FIXED32, offsetof(TelemetryMessage, field_4), NULL, NULL, (pb_field_long_t) 0},
    {0, PB_LTYPE_NONE, 0, NULL, NULL, 0}
};
