/* Automatically generated nanopb constant definitions */
/* Generated by custom CMake script from LoRa/docs/telemetry-message.proto */
/* This file MUST be regenerated if telemetry-message.proto changes */

#pragma once

#include <pb.h>

/* Defines for backward compatibility */
#define TelemetryMessage_size 16  /* 4 * uint32_t */

/* Struct definition */
typedef struct _TelemetryMessage {
    uint32_t field_1;
    uint32_t field_2;
    uint32_t field_3;
    uint32_t field_4;
} TelemetryMessage;

/* Default values for struct fields */
#define TelemetryMessage_init_default {0, 0, 0, 0}
#define TelemetryMessage_init_zero {0, 0, 0, 0}

/* Field tags (for use in manual encoding/decoding) */
#define TelemetryMessage_field_1_tag 1
#define TelemetryMessage_field_2_tag 2
#define TelemetryMessage_field_3_tag 3
#define TelemetryMessage_field_4_tag 4

/* Field descriptors for pb_encode/pb_decode */
extern const pb_msgdesc_t TelemetryMessage_msg;
extern const pb_field_t TelemetryMessage_fields[5];
